project_id = "vfcukxlzqfeehhkiogpf"

[functions.receive-email]
verify_jwt = false

[functions.afumail-api]
verify_jwt = false

[functions.ai-email-assist]
verify_jwt = false

[functions.telegram-miniapp-auth]
verify_jwt = false

[functions.telegram-miniapp-api]
verify_jwt = false

[functions.skypay-checkout-session]
verify_jwt = true

[functions.skypay-confirm-payment]
verify_jwt = true

[functions.skypay-webhook]
verify_jwt = false