// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-emails.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.83.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-emails.ts
var list_emails_default = defineTool({
  name: "list_emails",
  title: "List emails",
  description: "List the signed-in user's emails, newest first. Optionally filter by unread, starred, or a search term matching subject or sender.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("How many emails to return (max 50)."),
    unread_only: z.boolean().default(false).describe("Only return unread emails."),
    starred_only: z.boolean().default(false).describe("Only return starred emails."),
    search: z.string().trim().min(1).optional().describe("Match against subject or sender address.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, unread_only, starred_only, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("emails").select(
      "id, subject, from_address, to_addresses, is_read, is_starred, is_draft, received_at, sent_at, created_at"
    ).is("deleted_at", null).order("created_at", { ascending: false }).limit(limit);
    if (unread_only) query = query.eq("is_read", false);
    if (starred_only) query = query.eq("is_starred", true);
    if (search) query = query.or(`subject.ilike.%${search}%,from_address.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { emails: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-email.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_email_default = defineTool2({
  name: "get_email",
  title: "Get email",
  description: "Read one of the signed-in user's emails in full, including its body text.",
  inputSchema: {
    email_id: z2.string().uuid().describe("The id of the email to read.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ email_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("emails").select(
      "id, subject, from_address, to_addresses, cc_addresses, reply_to, body_text, body_html, is_read, is_starred, is_draft, received_at, sent_at, created_at, thread_id"
    ).eq("id", email_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No email found with that id." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { email: data }
    };
  }
});

// src/lib/mcp/tools/list-addresses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_addresses_default = defineTool3({
  name: "list_addresses",
  title: "List email addresses",
  description: "List the email addresses (and aliases) that belong to the signed-in user, including which one is primary.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("email_addresses").select("id, full_email, local_part, domain, is_primary, is_alias, created_at").order("is_primary", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { addresses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/update-email.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var update_email_default = defineTool4({
  name: "update_email",
  title: "Update email flags",
  description: "Mark one of the signed-in user's emails as read/unread, starred/unstarred, or important/not important.",
  inputSchema: {
    email_id: z3.string().uuid().describe("The id of the email to update."),
    is_read: z3.boolean().optional().describe("Set the read state."),
    is_starred: z3.boolean().optional().describe("Set the starred state."),
    is_important: z3.boolean().optional().describe("Set the important state.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ email_id, is_read, is_starred, is_important }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const patch = {};
    if (is_read !== void 0) patch.is_read = is_read;
    if (is_starred !== void 0) patch.is_starred = is_starred;
    if (is_important !== void 0) patch.is_important = is_important;
    if (Object.keys(patch).length === 0) {
      return {
        content: [{ type: "text", text: "Provide at least one of is_read, is_starred, is_important." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("emails").update(patch).eq("id", email_id).select("id, subject, is_read, is_starred, is_important");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: "No email found with that id." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0]) }],
      structuredContent: { email: data[0] }
    };
  }
});

// src/lib/mcp/tools/create-draft.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var create_draft_default = defineTool5({
  name: "create_draft",
  title: "Create draft email",
  description: "Create a draft email for the signed-in user. Drafts are not sent \u2014 the user reviews and sends them in the app.",
  inputSchema: {
    to: z4.array(z4.string().email()).min(1).describe("Recipient email addresses."),
    subject: z4.string().trim().min(1).describe("Subject line."),
    body_text: z4.string().trim().min(1).describe("Plain text body of the draft."),
    cc: z4.array(z4.string().email()).optional().describe("Optional CC recipients."),
    from_address_id: z4.string().uuid().optional().describe("Which of the user's addresses to send from. Defaults to the primary address.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ to, subject, body_text, cc, from_address_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let addressQuery = supabase.from("email_addresses").select("id, full_email, is_primary").limit(1);
    addressQuery = from_address_id ? addressQuery.eq("id", from_address_id) : addressQuery.order("is_primary", { ascending: false });
    const { data: address, error: addressError } = await addressQuery.maybeSingle();
    if (addressError) {
      return { content: [{ type: "text", text: addressError.message }], isError: true };
    }
    if (!address?.full_email) {
      return {
        content: [{ type: "text", text: "No sending address found for this account." }],
        isError: true
      };
    }
    const { data, error } = await supabase.from("emails").insert({
      user_id: ctx.getUserId(),
      email_address_id: address.id,
      from_address: address.full_email,
      to_addresses: to,
      cc_addresses: cc ?? null,
      subject,
      body_text,
      is_draft: true,
      is_read: true
    }).select("id, subject, from_address, to_addresses, is_draft");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? {}) }],
      structuredContent: { draft: data?.[0] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vfcukxlzqfeehhkiogpf";
var mcp_default = defineMcp({
  name: "fucha-mail",
  title: "Fucha Mail",
  version: "0.1.0",
  instructions: "Tools for the Fucha Mail email account of the signed-in user. Use `list_addresses` to see their addresses, `list_emails` to browse or search mail, `get_email` to read one message in full, `update_email` to change read/starred/important flags, and `create_draft` to prepare a message the user sends from the app. Nothing here sends email on the user's behalf.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_addresses_default, list_emails_default, get_email_default, update_email_default, create_draft_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
